User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
Python interpreter path: C:\Python39\python.exe
Starting Pylance language server.
> conda --version
> C:\Python39\python.exe -c "import pip"
> C:\Python39\python.exe -c "import pip"
Error 2021-08-31 22:10:26: Error in installing the module 'ipykernel', Error: Command failed with errors, check the terminal for details. Command: C:\Python39\python.exe -m pip install -U ipykernel
Traceback (most recent call last):
  File "c:\Users\maxo2\Documents\VSC-PROFILES\python\ms-python.python-2021.8.1159798656\pythonFiles\shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/Python39/python.exe', '-m', 'pip', 'install', '-U', 'ipykernel']' returned non-zero exit status 1.

> C:\Python39\python.exe -c "import ipykernel"
> C:\Python39\python.exe -c "import ipykernel"
> C:\Python39\python.exe -c "import pip"
> C:\Python39\python.exe -c "import pip"
Error 2021-08-31 22:11:23: Error in installing the module 'ipykernel', Error: Command failed with errors, check the terminal for details. Command: C:\Python39\python.exe -m pip install -U --force-reinstall ipykernel
Traceback (most recent call last):
  File "c:\Users\maxo2\Documents\VSC-PROFILES\python\ms-python.python-2021.8.1159798656\pythonFiles\shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/Python39/python.exe', '-m', 'pip', 'install', '-U', '--force-reinstall', 'ipykernel']' returned non-zero exit status 1.

> C:\Python39\python.exe -c "import ipykernel"
> C:\Python39\python.exe -c "import ipykernel"
Error 2021-08-31 22:16:44: Error while running worker[Worker 2]. undefined
Error 2021-08-31 22:16:44: Error while running worker[Worker 1]. undefined
